### ISSUE TITLE
Key via QR or Link - change timer plus encryption.

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#1019]
Can we directly exchange the ECDH secret via QR instead of doing the handshake (thereby doing away with expiry)?

**Comment by antuz123** [comment]
1. All QR (Keeper device and contacts) do not need a timer because it is encrypted with a much stronger key. Akin to AES key like used last time. But the data will be deleted in 24 hours. So a message will be added on the same (separate issue for message) 
2. All link sharing/ requests, we will also have a 24 hour time limit post which the ephemeral channel and the data will be deleted. A message will be displayed on the same as above. Here as the security is lower, we will encrypt with the key-stretch of the Hexa ID + Phone number (or email or OTP)

**Comment by antuz123** [comment]
@Parsh - see if what I have added makes sense. The delete button on expired contacts and message needed are outside this piece.

**Comment by cakesoft-swati** [comment]
need to be confirmed by developer.
