### ISSUE TITLE
Receiving address: Rotate receiving address across gap-limit

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#1211]

**Comment by antuz123** [comment]
Check what other wallets are doing here.

**Comment by antuz123** [comment]
Need some research on other wallets @Varunram

**Comment by Varunram** [comment]
Background: AGL is 20 inline with BIP-44. When AGL exceeds 20, the wallet software is expected to warn the user about this. Client software (electrum, btcpay, ledger, etc) follow BIP44 and as a result, implement this.

1. Electrum: generates addresses until AGL 20 and then you can generate more through the CLI
2. Offline wallets: behaviour seems to default to something like: "any address(es) generated more than the gap limit will not be automatically recovered. Same seems to be the case with most default wallets.

My suggestion is to: generate 20 addresses, show a new one in the wallet UI until the wallet reaches 20. Have a data structure that maps time of display to the address. When all 20 addresses have been displayed, sort the map in increasing order of timestamp and take the first address from the map (ie the address with lowest timestamp).

Fixes needed in receiving: Need to delete the receiving address from the map when you receive bitcoins.

When the number of addresses in the map exceeds a fixed number (eg. 5 or 10), wait for a specific period of time (eg. 3 days) before generating a new set of 20 addresses and resetting the map

**Comment by antuz123** [comment]
Question is not about use of the gap limit and recoverability. But also about how do the other wallets generate addresses on the receive screen. Is it the same as your proposal?

**Comment by Varunram** [comment]
We have to analyse the problem, and look at how we plan to fix it. In my understanding, the real problem is during recovery of wallets, and not during generation of addresses. The exact way other wallets do it doesn't matter as long as we solve the underlying problem (which may be what I identify or something else). If the exact way does matter, we are better off forking the repo

**Comment by antuz123** [comment]
We know where the gap limit gets used and why recovery is important. That is however not the question here. There are many ways in which the gap limit and its application to recovery can work. Obviously gap limit is used because you want a performant recovery. That is a given.

As there are different ways to achieve this, the market research item here is how do other wallets do it so that may be we learn from them and either have a better way of doing it or stuck to what you have proposed.

**Comment by Varunram** [comment]
If the requisite is looking at other wallets for how they implement a fix to the underlying problem, I think this issue should be re-assigned to an app-dev who can look at the code directly.

**Comment by antuz123** [comment]
Is this already done? @Parsh

**Comment by Parsh** [comment]
Addressed by NFA(next free address) issue

**Comment by cakesoft-swati** [comment]
- Closing this issue as discussed with dev.
