### ISSUE TITLE
Account Screens 

### ISSUE THREAD

**Issue by Parsh** [bithyve/hexa#1476]
- [ ] Donation account creation flow lands upon the Account Screen with checking account card being on the screen(as the carousel index defaults to 1 and we can't pass the newly created donation account index(>2) to account screen as the carousel would throw err due to non-static data).
- [ ] when I click on the Donation account, it lands upon the savings account.

**Comment by antuz123** [comment]
This is where we separate out the Account Screens to be their own entities so that the above UI bugs don't happen and it is much faster to load the Account Screens.

**Comment by CypherPoet** [comment]
@antuz123 @Parsh I think separating out the Account Screens to be their own entities is a _great_ thing to focus on for AC3 because it ties into so much -- Navigation, data loading, data modeling, etc -- that I [already have in motion there](https://github.com/bithyve/hexa/commit/2c523e58b4b430d496fa60ea49aedefdec7c816b) and will involve some significant refactoring.

[It would also imply removing the carousel](https://bithyve-workspace.slack.com/archives/CEBLWDEKH/p1601308262019300), which seems to be at the root of the bugs here.

With all that in mind, I'd recommend trying to find a quick fix here, and then making it an issue for AC3 to design/implement a long-term solution. Otherwise, I'd envision us duplicating a lot of effort here without much value.
