### ISSUE TITLE
Need UX for associate contact.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1490]
-Need UX
![needux](https://user-images.githubusercontent.com/62699947/92441590-1ff51800-f1cc-11ea-85ed-f30fb9da91b2.jpg)

**Comment by Parsh** [comment]
Have made the changes, however, they need to be improved upon(CSS part).

**Comment by AliMeer** [comment]
Need UX for this issue.

**Comment by Arpanjainson** [comment]
Refer to specs
https://xd.adobe.com/view/00485057-d5b7-4b2b-641b-20216b3a38d5-7679/screen/6fecdfd5-6f3e-463b-b6f0-0046f213c59f/

**Comment by Arpanjainson** [comment]
@antuz123  - review the specs and then assign the dev to Nikhita or Brian

**Comment by AliMeer** [comment]
@antuz123 There are a couple of associate contact issues I have seen with links to specs mentioned in them.
This issue seems to be an old one with a spec link from January.
Can we close this if this one is not required or if its old and ensure that we have only one issue for the associate contact screen?
