### ISSUE TITLE
PDF re-share 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#1605]
Not working on the upgraded app. Ali has now fixed it, needs to be tested thoroughly in the new release and with different scenarios. 

Re-sharing of pdf in an upgrade scenario (fixed by Ali but needs to be tested - for when the app reaches 100% and when the health <100%)

**Comment by cakesoft-swati** [comment]
-Tested upgrade scenario on android device,reshare is not working in this scenario.
1.I installed Staging app version 1.1.1.(98) and shared both the personal copies then confirmed it.After that I restored the wallet and upgraded it to latest version 1.1.2(112). Now in upgraded app I'm unable to attach pdf (sharing failed for other options).

-On ios device: It is showing Backup now button instead of confirm and reshare in upgraded app. Also it was showing red exclamation ark on folded card and on unfolded card it was showing grey exclamation mark with Back up now button.

**Comment by AliMeer** [comment]
https://github.com/bithyve/hexa/pull/1620

**Comment by AliMeer** [comment]
This should fix iOS status issue.
This also has a tactical fix for Android.

**Comment by cakesoft-swati** [comment]
Now after upgrading on both devices(android,ios), the Backup Now button appears instead of Confirm.
Tested on latest dev version 1.1.2(113)

**Comment by cakesoft-swati** [comment]
It is working now,tested on dev version 1.1.2(114) and also tested on staging app version 1.1.2(114)
