### ISSUE TITLE
UI changes on bottom sheet modals..

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1879]
-F&F has a cross while More has a back button. We need it to be consistent. 
![F Fcross](https://user-images.githubusercontent.com/62699947/97142485-b1254b80-1786-11eb-94f5-edc05070a7b5.jpg)

-The transactions has the heading in the middle while others have it left aligned.

**Comment by CypherPoet** [comment]
The difference between having an "x" button and an "arrow" depends upon how the view is being presented. 

For views that we're presenting modally (sliding up vertically), we're showing an "x", and for views that are being "stepped to" as the next view in a stack (sliding in from the right), we're showing a left arrow.

Right now, the F&F button on Home is presenting the F&F screen modally, hence the "x". Is the issue here to present it differently? (cc @antuz123 @AliMeer)

**Comment by AliMeer** [comment]
@CypherPoet yes that’s the issue. In addition the transactions screen has the title centre aligned whereas the rest of the modals/screens have left aligned titles.

**Comment by CypherPoet** [comment]
See follow-up discussion on the current design goals [here](https://bithyve-workspace.slack.com/archives/C018J9CUR1N/p1603730786014100?thread_ts=1603700688.003800&cid=C018J9CUR1N)

**Comment by cakesoft-swati** [comment]
-Now all the modal have centre aligned titles.

**Comment by CypherPoet** [comment]
> -Now all the modal have centre aligned titles.

@cakesoft-swati This will be fixed completely by the changes on #1861
