### ISSUE TITLE
App is opening in App store after clicking on add contact link.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1991]
-(User feedback) : Everytime he try to add contact from the link,all it ever does is open the App Store.
![File](https://user-images.githubusercontent.com/62699947/98328219-33c9c880-201b-11eb-9079-7048ed36daf9.jpg)

**Comment by antuz123** [comment]
The summary is that it does not open from Twitter. That’s it.

**Comment by Parsh** [comment]
@antuz123 I'm not sure what needs to be done here.

**Comment by AliMeer** [comment]
@Parsh we can check if this is still happening.
This is a very old issue so need to check if this is still a bug.

**Comment by Parsh** [comment]
What I've found is, when we send the link via Twitter, what twitter ends up doing is link shortning which is what is probably causing the issue.

I sent the following request to Ali sir on Twitter:
Click here to accept contact request from Bet' Hexa wallet - link will expire in 24 hours
https://hexawallet.io/dev/tc/Bet/46d9d7249ce9832c33fdab4e825d3d0befe941fa15b8406507059970c781dd473616ab3d6de25910a68aea54c18ffc395914fbe6f5a3fcc4862a2d0e138e009077959de25bd6381ad4dbf13157ab10cf/num/775/1616325388713/v1.5.0

And when I myself pressed the link, it was taking me to Hexa's website(404 page). Then I copied the F&F request message that I sent via Twitter and pasted it in slack, and it turned out to be the following:

Click here to accept contact request from Bet' Hexa wallet - link will expire in 24 hours
https://t.co/BL5nfbzy7v

**Comment by AliMeer** [comment]
This probably a solution for this issue https://stackoverflow.com/questions/46266797/deeplink-solution-for-ios-and-android-apps-works-in-facebook

**Comment by AliMeer** [comment]
This will require some more research will not be feasible to do it by Friday.

**Comment by AliMeer** [comment]
@antuz123 moving this out, this is not a quick fix. The conclusion is that Twitter changes the link when it is sent as a DM thats why it doesn't work. The change is done to shorten the link and because of that its not recognised as a deep link for Hesa by the mobile phone. The same happens in facebook as well.

**Comment by AliMeer** [comment]
The links functionality will fix this issue as well.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.80(488)
