### ISSUE TITLE
Fresh link and QR generation or Trusted Contact taking too long

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2099]
-Fresh link not generating for change contact on live app version 1.3.1(164).
![File (10)](https://user-images.githubusercontent.com/62699947/99631925-6f748180-2a62-11eb-9535-02525f4891df.jpg)
-It is working on latest staging app version 1.3.1(164)
-On live app,it is taking time to generate the link(almost 15 min)

**Comment by Parsh** [comment]
Links are working fine on Dev 1.3.1, however, in order to replicate the above scenario, I downloaded the latest live android version from App center(which is 1.3.1 build 164) and I'm actually not able to get past the screen given below, basically stuck at wallet creation.

![Screenshot_20201119-173854](https://user-images.githubusercontent.com/17980466/99664705-99dc3400-2a8e-11eb-8fd3-01622fbb89ce.jpg)

**Comment by AliMeer** [comment]
@Parsh please debug and identify the time-consuming steps in this process.

**Comment by cakesoft-swati** [comment]
-Unable to reproduce this issue on dev app v1.7.5(297)
-
