### ISSUE TITLE
F&F:Need the images from contact.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2117]
Need the images from contacts.

**Comment by cakesoft-swati** [comment]
<img width="375" alt="6412AA17-7C01-4EC8-9798-CC440845FE0A" src="https://user-images.githubusercontent.com/62699947/100201122-a5fc4180-2f25-11eb-955d-a5d751a71acf.png">
-Showing wrong image.Tested on Dev app version 1.3.2(170)

**Comment by AliMeer** [comment]
Lets test for avatar image.
This one is for F&F with no avatar image.

**Comment by CypherPoet** [comment]
I think this issue and https://github.com/bithyve/hexa/issues/1457 both require us to refactor the code so there's more clarity around how images are being fetched, stored, and read out for contacts. Right now, we're already trying a [myriad of guesses and fallbacks](https://github.com/bithyve/hexa/blob/1192b1914cf407b62c919bbba6ad07acb19e1e08/src/common/data/models/interfaces/RecipientDescribing.ts#L88), but I'd like to focus on a more clear and maintainable solution as part of #2039.

**Comment by CypherPoet** [comment]
So it looks like the latest way our code is trying to use contact images is by first checking for an `imageAvailable` flag on a `trustedContactsInfo` item, then trying to access an `image` property from the same item if it’s `true`. 

<img width="543" alt="Screen Shot 2021-03-17 at 9 11 33 AM" src="https://user-images.githubusercontent.com/46851636/111481458-fc71d380-8700-11eb-9f79-fb84ee0c3684.png">

I still can’t find how either of these are being initialized in the first place, though, which is what we would need to fix in order to access images for display in the UI here. (@AliMeer @Parsh)

**Comment by AliMeer** [comment]
@cakesoft-nikhita Can you explain how a contact image is retrieved and used?

**Comment by antuz123** [comment]
Spoke to Nikita, she is not able to figure where the image item went after the UI object and backend object related changes were made

**Comment by cakesoft-swati** [comment]
Duplicate of  #3171

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app v1.7.5(303)
