### ISSUE TITLE
Health is not updating after wallet recovery.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2144]
Health percentages are not updating after wallet recovery.
![Screenshot_20201125-131039_hexa dev](https://user-images.githubusercontent.com/62699947/100197787-dab9ca00-2f20-11eb-9612-08c62af044c6.jpg)

**Comment by Parsh** [comment]
Health is updating fine when the wallet is recovered using contacts on iOS.
![Simulator Screen Shot - iPhone 11 - 2020-11-25 at 14 06 11](https://user-images.githubusercontent.com/17980466/100204884-6f74f580-2f2a-11eb-819b-30aec40204c0.png)

@cakesoft-swati to confirm whether the health is working fine when an iOS wallet is recovered using PDFs. If it does, then the issue is specific to Android(just like the transient 50% health issue on fresh Android build install)

**Comment by cakesoft-swati** [comment]
I tested on both the devices.This issue is specific to Android.

**Comment by antuz123** [comment]
I also assume that this is something that goes away once you re-login? I am pushing it post Keeper with that assumption, if that's not the case then please reopen this @cakesoft-swati

**Comment by cakesoft-swati** [comment]
-Verified this issue on live app version 1.3.2(175)
