### ISSUE TITLE
UI changes of Home screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2219]
![image](https://user-images.githubusercontent.com/62699947/101442512-7693fe80-3941-11eb-84a8-4bd9339e3829.png)

[XD link]
https://xd.adobe.com/view/f11ac530-31c1-477d-adf4-22524b8b7ed3-a449/screen/4c3e1e2f-8673-468c-ab39-f39929fd6e64/
[Issues to be handled -
1, 2, 3, 4, 5, 6, 7, 9, 10, 11.
8 will handled later once we have the new account management in place].

**Comment by CypherPoet** [comment]
@cakesoft-swati Could we get a more higher-resolution image attached to this issue? I'm having trouble reading many of the items and seeing what exactly they refer to.

**Comment by CypherPoet** [comment]
https://github.com/bithyve/hexa/pull/2354 is meant to address most of the points here. 

A few notes on some of the points, though:

- 4 & 5) The spacing is set to 14, which is what I’m seeing in the latest design.

- 6: The spacing here is always going to be somewhat dynamic, because we always want any potential overflowing columns to be peeking inwards.

**Comment by cakesoft-swati** [comment]
-Verified this on Dev app v1.4.1(192)
