### ISSUE TITLE
UI changes of "More" screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2220]
![image](https://user-images.githubusercontent.com/62699947/101443153-bf988280-3942-11eb-87c0-870f70bd34be.png)

[XD link]
https://xd.adobe.com/view/f11ac530-31c1-477d-adf4-22524b8b7ed3-a449/screen/3765f819-d965-4601-b807-34a381512f56/
[Issues to be handled -
all 1,3,4,5,6,7,8,9 except 2 which needs to be discussed with Brian and Anant.
 ]

**Comment by CypherPoet** [comment]
@cakesoft-swati Could we get a more higher-resolution image attached to this issue? I'm having trouble reading many of the items and seeing what exactly they refer to.

**Comment by CypherPoet** [comment]
https://github.com/bithyve/hexa/pull/2356/files is meant to address most of the points listed here. Regarding some other points:

5) This seem to be a typo — there’s no icon being referenced.

6) This seem to be due to the fact that we aren’t showing all of the items yet.

8 & 9) These changes are related to our decision to make “More” a navigable screen instead of a bottom sheet.

**Comment by cakesoft-swati** [comment]
-Verified these issues on Dev app v1.4.1(192)
