### ISSUE TITLE
UI changes of Donation Account Setup screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2223]
![image](https://user-images.githubusercontent.com/62699947/101444079-b9a3a100-3944-11eb-919d-ce9870f384eb.png)

[XD link]
https://xd.adobe.com/view/f11ac530-31c1-477d-adf4-22524b8b7ed3-a449/screen/f63f2aec-96c8-47bc-9394-e96a13ff53ad/

**Comment by CypherPoet** [comment]
@cakesoft-swati Could we get a more higher-resolution image attached to this issue? I'm having trouble reading many of the items and seeing what exactly they refer to.

**Comment by AliMeer** [comment]
@CypherPoet the XD Link (https://xd.adobe.com/view/f11ac530-31c1-477d-adf4-22524b8b7ed3-a449/screen/f63f2aec-96c8-47bc-9394-e96a13ff53ad/)has a high res version. Let me know if you still face issues and I will send you a high res version.

**Comment by CypherPoet** [comment]
@AliMeer Oh, nice -- I didn't realize that's where the image was from, my bad 😄

**Comment by CypherPoet** [comment]
@Arpanjainson @cakesoft-swati The latest design file I found is https://xd.adobe.com/view/00485057-d5b7-4b2b-641b-20216b3a38d5-7679/screen/8dff66c7-2637-4cc2-acec-36f05ebcad7e/specs/.

But this is also different than what is shown as the "Visual Design" in the issue here. Do we know for sure what the correct design file is?

**Comment by antuz123** [comment]
The difference seems to be only when the keyboard is not there. Rest seems to be same. 

@CypherPoet - I suggest look at each point as an example of what seems to be the discrepancy across the app between VD and what we have implemented. Then implement it across the app if we find the UX suggestion makes sense.

**Comment by CypherPoet** [comment]
@antuz123 For sure, but my confusion is mainly regarding what the latest design spec is. There's a spec shown in the screenshot above, but there's also a different spec [here](https://xd.adobe.com/view/00485057-d5b7-4b2b-641b-20216b3a38d5-7679/screen/8dff66c7-2637-4cc2-acec-36f05ebcad7e/specs/)

**Comment by CypherPoet** [comment]
Okay, so the changes on #2353 are meant to address many of the points listed here.

Regarding the text-input shadow change on focus, I would recommend making separate issue for implementing this as a component and applying it throughout the app.

Regarding placing the "Proceed" button on the button of the screen, this poses some challenges because we also want to have the button slide up when the keyboard is shown, and when we also want to have the entire screen be part of a scroll view. For now, I'd suggest considering how the interaction works while keeping the button naturally right below the bottom of the other content.
