### ISSUE TITLE
Proceed Button on Add new Account too  lower down on the screen and is being cut off

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#2279]
Proceed Button on Add new Account too lower down on the screen and is being cut off.

Test Device: iPhone 12 Pro Max and iPhone XS
Test Version: v1.4.0. # 179, 181 and 182

![IMG_0053](https://user-images.githubusercontent.com/7535475/101991878-695f7280-3ca7-11eb-86e7-14371c456af2.PNG)

**Comment by CypherPoet** [comment]
Some of the changes on https://github.com/bithyve/hexa/pull/2335 were also meant to improve this. I'm going to mark the issue as fixed, but if it's still a concern on future build, @AliMeer, @antuz123, @Arpanjainson, I think there needs to be a deeper discussion about how to design this screen differently -- because at this point, we're running up against the constraints presented by all the other content on the screen.

**Comment by cakesoft-swati** [comment]
-Verified this issue on dev app version 1.4.0(190)
