### ISSUE TITLE
Account settings: Archive Account 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#2332]
1. A user should be able to archive an account. 
2. The system checks if there is a balance if there is then a message is displayed to empty the account first and the process closes. 

1.a. The user will have to come in again empty it and then try archiving it. 

3. The archived accounts are still visible in the 'Account Management' in More as greyed out accounts. They cant be moved around but when you touch the account, you can "Put it back". This pushes the account on the home screen. It does not have any other option.

**Comment by CypherPoet** [comment]
After our discussion today, I think we still need more clarity here before the UI can be implemented.

- From what I heard, we want a new “Account History” screen that’s accessible from More > Account Management… and then clicking on one of the items listed - and that’s where the “Archive” option will exist. Is this correct? If so, is there a design for how some kind of “Archive” option or button would be presented?

- Regarding:
  > The archived accounts are still visible in the 'Account Management' in More as greyed out accounts. They cant be moved around but when you touch the account, you can "Put it back”

  I'm not entirely sure how this would be implemented within the current re-orderable list. How would re-ordering work if some items can’t be moved? (Because moving anything has the potential to change the relative order of anything else)

@Arpanjainson @antuz123 @AliMeer

**Comment by antuz123** [comment]
@CypherPoet - for the second point, the archived accounts can be last in the list and may not have the handlers to move the account. Or if the reordering gets triggered by a button on the top right called "rearrange" then the archived accounts may be hidden if that happens. The top right "rearrange" button may be needed to get the accounts in rearranging mode as by default they might have a '>' as a way to get into the Account Log screen. 

@Arpanjainson - we need the UX for 
1. the "Account Log" screen that is accessible from the Account Management. This screen can also be made visible from the account settings as well but the rearranging will happen only from More and so we can have some advanced features as well. 
2. the "Account Management" screen where reordering happens and with the option of greying out a few accounts as they are archived


@CypherPoet - I suggest you read through this but wait for the UX to come back for this one as there seem to be several options.

**Comment by Arpanjainson** [comment]
Look for screens in the proto and later in specs
https://xd.adobe.com/view/181f3fd2-7aca-4284-61c7-3417e1fe6d8a-6e2e/screen/fdce57c9-114c-41d7-80c4-c24f6b1158ee
Checking Account – Settings – Archive
Checking Account – Settings – Archive Error
More – Account Management
More – Account Management – Un Archive
Success Screen – Un Archive

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (286)
