### ISSUE TITLE
UI issues of "Add New Account" screen.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2391]
-There is something still not right about this screen to go to market with.
1. The top line should fit in one -“Add an account, service or import a wallet”
2. The account icons are still not aligned properly. Coming Soon should not change the icon position
3. Is Proceed button positioned as it should be?
4. The Whirlpool account should go for now. Replace it with “Collaborative Custody”. Need a proper icon for it.
4. Are the icons too small as compared to the UX design? Radio buttons too big?
![File (20)](https://user-images.githubusercontent.com/62699947/103350099-d73bd480-4ac4-11eb-836e-027427706580.jpg)

**Comment by CypherPoet** [comment]
https://github.com/bithyve/hexa/pull/2423 addresses many of the issues here. Some additional notes:

- The “Coming Soon” text isn’t changing the position of the icon. The icon and main text are justified to be vertically and horizontally centered, so the icon is higher when there’s more text below it. Given that, I’m not quite sure this is an issue.
- We still need a proper icon for the “Collaborative Custody” item. Also, is there a specific subtitle we want to use here?
- I raised the Proceed button to be higher up than designed because we were also [considering it a bug that it was being cut off](https://github.com/bithyve/hexa/issues/2279) on smaller devices. The [comment I left on that issue](https://github.com/bithyve/hexa/issues/2279#issuecomment-748243543) explains where I think this needs more design and UX considerations.

(@antuz123 @Arpanjainson @AliMeer)

**Comment by cakesoft-swati** [comment]
-Verified this issue on Dev app version 1.4.1(192)
