### ISSUE TITLE
Can not send the whole balance without overpaying on fees.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2618]
From user :
I can't send my whole balance without overpaying on fees. I want to set it at 4 sats per byte. I don't care when it confirms, I don't care if it gets kicked. I have to select send max, which auto calculates a crazy high fee, or I can't select a custom rate for the fee. If I type any amount just under the wallet balance it fails the payment. Very frustrating. I either have to overpay on fees or create dust. It's a lose, lose situation. I should be able to select the whole balance and it subtract the fee from that amount. Why it has to calculate a fee before I even have the option to select a custom rate is confusing to me.

**Comment by bacchus42** [comment]
the same happens to me. today the rate is showing, no matter how much you try to send, 532%. In other words, I was going to owe money trying to send the same to another place. This has no logic whatsoever. Not to mention that he has not accepted to put the amount that I have available, because it gives the message that not enough funds for the transaction

**Comment by Parsh** [comment]
Need a mechanism to enable custom fee during the send max flow

**Comment by Arpanjainson** [comment]
was able to send using custom fee  lowest 1 sat/byte in test account during send max flow.
