### ISSUE TITLE
T & C Updation for data being collected

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#3116]
While allowing the wallet to access Google Drive, Google gives a message to users to check what data Hexa is collecting. We need an answer to this to update our T & C.

![Google Play T   C](https://user-images.githubusercontent.com/68264080/113594049-c5824400-9654-11eb-9261-36e60b3f0dd9.jpg)

**Comment by antuz123** [comment]
1. What data are we collecting? 
2. What happens when someone un-checks the tick above

**Comment by cakesoft-utkarsh** [comment]
We can request Google Drive read and Write access without access to public PII data on Google account.
But the Hexa app crashes and not able to back up without this. Which should be corrected since we are not using user email or any other personal information.

**Comment by cakesoft-utkarsh** [comment]
To answer Anant's Question.
1. What data are we collecting?
We are not collecting but requesting Public personal information on a google account.

2. What happens when someone un-checks the tick above
Unchecking the 4th Check box "See, Create, and Delete...." will fail the backup. That's the only access we need to save Backups on Google.

3. Are those links work properly
Yes, those links take the user to hexawallet URLs. 

4. Can we not have this warning?
This pop up is unavoidable. Though as mentioned above comment we cannot ask for PII data associated with the Google account.
@antuz123

**Comment by antuz123** [comment]
@cakesoft-utkarsh - got it. But need to make sure this does not crash the app. Can we look into it

**Comment by cakesoft-utkarsh** [comment]
Sure,
@cakesoft-nikhita Can you please check why the app crashes if we remove email requests?

**Comment by cakesoft-devika** [comment]
-Verified this issue on Dev app v1.7.0 (286)
