### ISSUE TITLE
The restore is not working with old recovery keys.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#3123]
--I had an old app 1.4.4 (226) I upgraded it to 1.5.0 (260). Then I shared the recovery keys and after that I moved to Restore Flow. Then I saw the new restore screen, which is in NBHR. I scanned one of the old recovery keys. He showed me the loader and then nothing happened.

**Comment by cakesoft-nikhita** [comment]
This issue is fixed by our current conditions. We are assuming Cloud Backup is compulsory So When a user goes to RestoreFlow first user try to check if the backup is available
1) If the backup is not available then the user moves to Get wallet name and get Question and move to old flow. 
2) If backup found user needs to choose which wallet needs to backup and then it will ask a question and then our new flow started

**Comment by cakesoft-devika** [comment]
- Closing this issue as we can't test OBHR restore flow in Dev app v1.7.0 (286)
