### ISSUE TITLE
Possible errors occurring while iCloud/Google Drive backup and error handling

### ISSUE THREAD

**Issue by cakesoft-priyanka** [bithyve/hexa#3544]
### Description:
Identify possible errors occurring while iCloud/Google Drive backup and handle them with proper messages so that the users can troubleshoot them or know the cause of backup failure.

**iCloud backup issues:**
Reference links:
https://support.apple.com/en-in/HT203271
https://www.makeuseof.com/tag/common-icloud-problems/
1. Cannot connect to iCloud
2. iCloud authentication error
3. Unsupported device or Apple ID
4. Insufficient iCloud storage space
5. Verification failed
6. iCloud backup is disabled
7. An error occurred
8. Backup is corrupt or incompatible

**Google Drive issues:**
1. Google Drive sign in error code
2. Connection failure
2. Insufficient Google storage
3. Google Drive is not syncing
4. Google Drive app might be outdated
5. Corrupt app data

**Comment by cakesoft-nikhita** [comment]
Below list is for Google Drive

- Google Drive SignIn error codes 
[(https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes#SIGN_IN_REQUIRED)]

- For  Insufficient Google storage etc please refer to this
[(https://developers.google.com/drive/api/v3/handle-errors)]

- Google Drive is not syncing: its handle in code as if it's not syncing it will throw an error and it will ask again login id of Gmail

**Comment by antuz123** [comment]
@cakesoft-shashank - can you look fat what error codes we get back for the above errors described. If we get the error codes back, we will design messages around them

**Comment by cakesoft-shashank** [comment]
@antuz123 @cakesoft-priyanka please find iCloud error codes here: https://developer.apple.com/documentation/cloudkit/ckerrorcode?language=objc

**Comment by cakesoft-shashank** [comment]
There will be "hexa error codes" which will be mapped to the error codes that can be thrown by iClould/google drive

**Comment by cakesoft-shashank** [comment]
case '36': //An error that occurs when the user's iCloud account is temporarily unavailable.
        return 'iCloud account is temporarily unavailable, please try after sometime.'
      case '25': //An error that occurs when saving a record exceeds the user's storage quota.
        return 'Storage quota exceeded.'
      case '21': //An error that occurs when the change token expires.
        return 'Please check authentication with iCloud in settings and try again.'
      case '19': //An error that occurs when the server rejects the request because of a unique constraint violation.
        return 'Please try again after sometime.'
      case '18': //An error that occurs when the current app version is older than the oldest allowed version.
        return 'Please update your app and try again.'
      case '27': //An error that occurs when a request's size exceeds the limit.
        return 'Request limit exceeded, please try after sometime.'
      case '4': //An error that occurs when a network is available, but CloudKit is inaccessible.
        return 'Network error, please try again.'
      case '3': //An error that occurs when the network is unavailable.
        return 'Network error, please check your internet connection.'
      case '7': //An error that occurs when CloudKit rate-limits requests.
        return 'Request limit exceeded, please try after sometime.'
      case '9': //An error that occurs when the user is unauthenticated.
        return 'Unauthenticated, please check authentication with iCloud in settings and try again..'
      default:
        return 'Please try again after sometime.'
        
 @ASN-BitHyve please refer to this. '//' marked lines are explanation of the error and 'return' lines are the short user centric message.

**Comment by cakesoft-shashank** [comment]
## Google drive backup error codes
- API_NOT_CONNECTED(17)
The client attempted to call a method from an API that failed to connect. Possible reasons include:
The API previously failed to connect with a resolvable error, but the user declined the resolution.
The device does not support GmsCore.
The specific API cannot connect on this device.

- CANCELED(16)
The result was canceled either due to client disconnect or PendingResult

- CONNECTION_SUSPENDED_DURING_CALL(20)
The connection was suspended while the call was in-flight.
It is possible this failure could be resolved by retrying.

- DEVELOPER_ERROR(10)
The application is misconfigured. This error is not recoverable and will be treated as fatal. The developer should look at the logs after this to determine more actionable information.

- ERROR(13)
The operation failed with no more detailed information.

- INTERNAL_ERROR(8)
An internal error occurred. Retrying should resolve the problem.

- INTERRUPTED(14)
A blocking call was interrupted while waiting and did not run to completion.

- INVALID_ACCOUNT(5)
The client attempted to connect to the service with an invalid account name specified.

- NETWORK_ERROR(7)
A network error occurred. Retrying should resolve the problem.

- RECONNECTION_TIMED_OUT(22)
The connection timed-out while attempting to re-connect.
This failure indicates a connection to Google Play services was successfully established, however it was disconnected for some reason (for example, Google Play services crashed), and re-connecting took longer than expected.
Any API calls failed with this status would have been initiated after the connection was disconnected.

- RECONNECTION_TIMED_OUT_DURING_UPDATE(21)
The connection timed-out while waiting for Google Play services to update.
This failure indicates a connection to Google Play services was successfully established, however it was disconnected because Google Play services was updated, and the update took far longer than expected.
Any API calls failed with this status would have been initiated after the disconnection for the update.

- REMOTE_EXCEPTION(19)
This signifies that an API was able to connect to Google Play services and received an instance, but that when calling an individual method, a RemoteException was thrown.

- SERVICE_DISABLED(3)
The installed version of Google Play services has been disabled on this device. 

- SERVICE_VERSION_UPDATE_REQUIRED(2)
The installed version of Google Play services is out of date. 

- SIGN_IN_REQUIRED(4)
The client attempted to connect to the service but the user is not signed in. 

- TIMEOUT(15)
Timed out while awaiting the result.

@ASN-BitHyve please check

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.0(353) also as discussed with dev closing this issue.
