### ISSUE TITLE
QR requests screen

### ISSUE THREAD

**Issue by cakesoft-priyanka** [bithyve/hexa#3553]
### Description:
The QR will have the Hexa logo in the center and two words like ‘F&F Request’ for all types of QR.

Display heading/ subheading as follows:
a. Above QR. Heading: "Scan QR" Subheading: "With your contacts Hexa app"
b. Above Link: "Share link" Subheading: "With the contact"

Need to add an option at the bottom: "Secure with 2FA". If tapped, an option opens up where the user can choose OTP or Confirm Phone Number or Confirm email. (Phone number and email may not be present) When the user selects any one, the QR or link on the screen changes and the selected option is shown at the bottom.

### Specs Link:
https://xd.adobe.com/view/182db13e-dc6a-40ec-a319-5bf018182399-4d7e/screen/c08dd9e9-baa9-4376-b115-c3e3a94dc843/

**Comment by antuz123** [comment]
Do the QR image

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/182db13e-dc6a-40ec-a319-5bf018182399-4d7e/screen/c08dd9e9-baa9-4376-b115-c3e3a94dc843/

**Comment by antuz123** [comment]
@Parsh - note here that when the 2FA is chosen, even the QR changes. Not just the link

**Comment by cakesoft-rohit** [comment]
1. Depending on what data the user has, this screen will show options. E.g. if the contact does not have an email ID, it will not show that option.
2. OTP is always shown.
3. Below each option (instead of Lorem Ipsum) the actual phone number or email address is shown. As example Contact name’s phone number: 8363829994. OTP is also shown
4. Depending on what the user selects, the data is encrypted with that option

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v1.9.5(330)
