### ISSUE TITLE
keeper request to an existing f&f

### ISSUE THREAD

**Issue by cakesoft-priyanka** [bithyve/hexa#3560]
### Description:
1. When the user is sending a Recovery Key they directly come to the screen where they are selecting someone from the Address Book.

2. We want to give them an option to select an existing F&F also where they will select an existing F&F and then don’t need to select from the address book.

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/182db13e-dc6a-40ec-a319-5bf018182399-4d7e/screen/fae1674f-4ef4-42b1-9311-871427c4a328/

**Comment by antuz123** [comment]
@summikhan11 - we don't need the filters on the top. We are not using them anywhere. There will be a handful of F&F only at the max. Also most of the time they will not have F&F but will add from the address book. So the bottom area is too big. 

Also, need the Address Book symbol instead of the plus button as discussed. 

Can we show the address book at the bottom with the F&F list on the top like a horizontal selection? As they will be few.

**Comment by summikhan11** [comment]
https://xd.adobe.com/view/182db13e-dc6a-40ec-a319-5bf018182399-4d7e/screen/22199a7f-0690-410a-9bba-5a07e4c7e007/

scroll to find a variation where there's limited contacts

**Comment by cakesoft-swati** [comment]
- Verified this flow on dev app v2.0(349)
