### ISSUE TITLE
Cloud backup.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4463]
- Not a correct CTA when cloud is already backed up. Need to show only when not initially backed up.
<img width="375" alt="D49E0B6A-C9AA-45E1-9E1D-FF287CF3C4E8" src="https://user-images.githubusercontent.com/62699947/135051485-c421c8ae-749b-441b-acd1-d3162b5fd4db.png">

**Comment by cakesoft-shivani** [comment]
**Scenario1:**
The note will change to be:
(When backup is successful)
Cloud Backup
Your have successfully backed up on the cloud. You don't have to do anything.  (edited) 


**Scenario 2:**
(Before backup)
Cloud Backup
You can backup on the cloud and use the Recovery Key from the cloud when restoring.
(Here the CTA is shown) 


**Scenario 3a and 3b:**
(When the backup is IA - time expiry or when you try to change levels and cloud is not available)
CTA = Confirm


**Note:**
Cloud Backup
You need to confirm your cloud connection, to ensure backup is accessible when you need it.
In this scenario, Confirm will
Just check the cloud connection and if the RK is there (on time expiry)
Do the changes to the RK as needed due to Level change or Keeper change etc

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.1(373)

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.01(374)
-
