### ISSUE TITLE
Not able to create the gift of 1000sats.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4913]
- I'm trying to create the gift of 1000 stas without fee but when I click on "Create Gift" it doesn't go beyond the model.

**Comment by Parsh** [comment]
@cakesoft-swati @antuz123 
I've been able to generate a 1000 sats gift as can be seen in the screenshots(but yes, earlier I've seen it failing w/ node throwing a dust limit err due to high fee back then). Therefore, we might have to increase the minimum sats for Gift to avoid this situation.

Also, we need a UI modal that reflects that the creation process has failed, rather than the creation bottom sheet being shown perpetually. 

![Simulator Screen Shot - iPhone 12 mini - 2021-11-29 at 11 33 34](https://user-images.githubusercontent.com/17980466/143841085-54a65e11-6d2e-413b-b071-988c94a4500b.png)
![Simulator Screen Shot - iPhone 12 mini - 2021-11-29 at 11 33 45](https://user-images.githubusercontent.com/17980466/143841105-5b039122-31c5-425f-8e40-e0c68aa7b0f8.png)

**Comment by antuz123** [comment]
@Parsh - please use a toast message to show failure when this happens. "Transaction failed due to dust limit. Please increase the gift amount and try"

**Comment by Parsh** [comment]
Toast applied
> @Parsh - please use a toast message to show failure when this happens. "Transaction failed due to dust limit. Please increase the gift amount and try"

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.7(396)
