### ISSUE TITLE
Post restore account issues.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#5315]
- [x] When the app is restored on another device, the accounts are now visible, however, the send from the savings account was failing with the Transaction Signing failed: could not find private key error.
- [x] On hard-refreshing the savings accounts(as the hard-refresh fixed the send error from Checking), it showed zero balance with all transactions showing zero amount(whether it was incoming or outgoing) and many transactions were duplicate(same txid).
- [x] On the restored app, the sweep flow also doesn't seem to work, it gets stuck after scanning the approval key and never navigates to the send screen.

**Comment by Parsh** [comment]
There were a few backup issues resulting in the above err:
- The first two issues were caused by is2FA flag(in accounts) being not backed up and therefore unavailable during restoration.
- The sweep funds on the restored was primarily not working as the smShare(1st share of the secondary mnemonic) wasn't available in the WI and therefore the secondaryXpriv was failing to generate even after scanning the approval key(containing the 2nd share). Also, the details2FA variable was not getting backed up which could have lead to setting up savings account(by scanning the 2FA key and validating using authenticator) fail on the restored app.

**Comment by cakesoft-swati** [comment]
- Verified this issue on dev app v2.0.69(429)
