### ISSUE TITLE
Review notifications

### ISSUE THREAD

**Issue by summikhan11** [bithyve/hexa#5443]
Can we have a list of all notifications that should be displayed here

https://xd.adobe.com/view/8c2960b0-14d1-4e00-a464-91e7d8219524-d97a/

**Comment by antuz123** [comment]
The message centre along with notification capability should support the following message types:

F&F request response - this can be accepted or rejected. CTA = Ok
F&F Keeper request - making the F&F as a Keeper. CTA = Accept/ Reject
F&F transaction - a txn made from a contact. CTA = Go to Account
Release Broadcast - a release broadcast is avaIlable and triggered from Relay. CTA = Upgrade
// FNF_REQUEST_ACCEPTED
// FNF_REQUEST_REJECTED
// FNF_KEEPER_REQUEST
// FNF_KEEPER_REQUEST_ACCEPTED
// FNF_KEEPER_REQUEST_REJECTED

**Comment by antuz123** [comment]
List of notifications:

F and F:

F and F request coming in
F and F request going out
F and F request accepted
F and F request rejected
Transaction:

Sats coming in
Sats going out
Transaction failing
Batch send successful
Batch send fail
Sats shifted from one account to another one
Sats coming into Swan account due to auto DCA
Suggestion: The icon should suggest in what account money has come in. This would especially be useful when someone is collecting donations. Maybe the Account's default color could be used in some way for the purpose.
Backup:

Passcode requires attention
Cloud backup requires attention
Personal Device 1 requires attention
Secondary Device 1 requires attention
PDF backup requires attention
Secondary Device 2 requires attention
Keeper Request Accepted
Keeper Request Rejected
A reminder that a Keeper Request was sent but it was neither accepted nor rejected
Keeper Request received
Personal Device (Level 2 RC 1) inaccessible
There could be separate icons or just a common icon with different messages for backup.
Gift:

Gift received
Gift rejected (Ouch!)
Sent gift expired

**Comment by antuz123** [comment]
Once the flow is corrected and is performant, see how we are placing them in the notification centre and marking them read or un-read.
